### PR TITLE
encoding implementation doesn't require complicated TLV parsing

### PR DESCRIPTION
**Pull request by fiatjaf**

### CODE REVIEW

**Comment by fiatjaf** [comment]
@paulmillr I'm getting an error `Uncaught RangeError: start offset of Uint32Array should be a multiple of 4` when decrypting and I don't understand it.

```
nonce = Uint8Array(24) [
  227, 144, 200,  24, 212, 184,  98,
  148,  48,  79, 139, 249, 133, 133,
    9, 185,  32, 211, 235,  48,  78,
  129,  25, 165
]
ciphertext = Uint8Array(11) [
  138, 135, 172, 137,  35,
   44, 123,  51,  63, 170,
   46
]
shared key = Uint8Array(32) [
   79, 33,  50, 241, 175,  59,  37, 199,
  138, 28, 237,  60,  66,  21,   9, 187,
  174, 56,  22, 190,  93, 228, 191, 232,
  156,  9,  22,  11, 122, 248,  42, 199
]
```

The full stack trace is this:

```
error: Uncaught RangeError: start offset of Uint32Array should be a multiple of 4
    at new Uint32Array (<anonymous>)
    at u32 (file:///home/fiatjaf/comp/misc/node_modules/.deno/@noble+ciphers@0.2.0/node_modules/@noble/ciphers/esm/util
s.js:6:29)
    at hchacha (file:///home/fiatjaf/comp/misc/node_modules/.deno/@noble+ciphers@0.2.0/node_modules/@noble/ciphers/esm/
chacha.js:115:17)
    at file:///home/fiatjaf/comp/misc/node_modules/.deno/@noble+ciphers@0.2.0/node_modules/@noble/ciphers/esm/_salsa.js
:105:17
    at decrypt (file:///home/fiatjaf/comp/misc/main.ts:44:21)
    at file:///home/fiatjaf/comp/misc/main.ts:55:11
```

Any help is appreciated, sorry for my laziness, this is probably some stupid mistake.

**Comment by staab** [comment]
Closed, I ported the changes over manually, but I'm getting the same misalignment error, @paulmillr?

**Comment by paulmillr** [comment]
@staab @fiatjaf You should do `.slice()` instead of `.subarray()` in the code above for now. We have this limitation for good perf, for now.

**Comment by fiatjaf** [comment]
Damn.

**Pull request closed without merging**
